---
- hosts: all
  tags:
    - bootstrap
  vars:
    docker_version: "18.02.0~ce-0~ubuntu"
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - name: Install Docker
    include_role:
      name: ansible-docker-ubuntu
- hosts:
    - master
    - validators
  tags:
    - bootstrap
    - generate_keys
  vars:
    # Overwrite exsiting keys or not
    overwrite: true
    # Path to write keys to
    path: "{{ playbook_dir }}/keys"
  tasks:
  - name: Generate keys
    include_role:
      name: geth-key
    vars:
      account: "{{ inventory_hostname }}"
      path: "{{ path }}"
    delegate_to: localhost
