---
- hosts: all
  tags:
    - bootstrap
  vars:
    docker_version: "18.02.0~ce-0~ubuntu"
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - include_role:
      name: ansible-docker-ubuntu
